services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      postgres:
        condition: "service_healthy"
    labels:
      - "traefik.enable=true"

      # cloudflare経由のルーティング
      - "traefik.public=true"
      - "traefik.http.routers.vaultwarden-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.vaultwarden-public.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-public.tls=true"
      - "traefik.http.routers.vaultwarden-public.tls.certresolver=le"
      - "traefik.http.routers.vaultwarden-public.middlewares=access-allow-chain@docker"

      # vpn経由のルーティング
      - "traefik.private=true"
      - "traefik.http.routers.vaultwarden-private.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.vaultwarden-private.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-private.tls=true"
      - "traefik.http.routers.vaultwarden-private.tls.certresolver=le"
      - "traefik.http.routers.vaultwarden-private.middlewares=access-allow-chain@docker"

    environment:
      - "WEBSOCKET_ENABLED=true"
      - "DOMAIN=https://${APP_HOST}"
      - "DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/vaultwarden"
      - "SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_FROM=${SMTP_FROM}"
      - "SMTP_PORT=587"
      - "SMTP_SECURITY=starttls"
      - "SMTP_USERNAME=${SMTP_USER}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "SMTP_AUTH_MECHANISM=Login"
    volumes:
      - "vaultwarden-data:/data"
    networks:
      - "default"
      - "public-traefik"
      - "private-traefik"
  postgres:
    image: docker.io/library/postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: vaultwarden
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d vaultwarden"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - "default"
volumes:
  vaultwarden-data:
  postgres-data:
networks:
  private-traefik:
    external: "true"
  public-traefik:
    external: "true"
